version: "3.8"

services:
    db:
        image: postgres:14
        env_file:
            - .env
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - db_data:/var/lib/postgresql/data

    web:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        env_file:
            - .env
        depends_on:
            - db # Specify that 'web' depends on 'db'

volumes:
    db_data:
