version: "3.8"

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - .:/app # Mount the current directory to the /app directory in the container for live reloading
        env_file:
            - .env
        depends_on:
            - db # Specify that 'web' depends on 'db'

    db:
        image: postgres:14
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - db_data:/var/lib/postgresql/data

volumes:
    db_data:
